FROM golang:latest AS builder

# Set up the build environment
RUN mkdir -p /app
WORKDIR /app

COPY . /app/

# Install Golang CLI tools
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# Handle schema generation
RUN sqlc generate --file internal/db/sqlc.yaml

# Build the final app
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-w -s" -o bin/scheduled-tasks ./cmd/tasks

CMD ["./bin/scheduled-tasks"]