version: '3'

dotenv: ['.env']

tasks:
  build:api: go build -ldflags "-w -s" -o bin/api-backend.exe ./cmd/api
  build:tasks: go build -ldflags "-w -s" -o bin/scheduled-tasks.exe ./cmd/tasks
  sqlc: sqlc generate --file internal/db/sqlc.yaml
  swag:
    cmds:
      - swag fmt
      - swag init --parseDependency -dir ./api --output ./internal/docs
  migrate:up: migrate -path internal/db/migrations -database "{{ .POSTGRES_URL }}" up
  migrate:down: migrate -path internal/db/migrations -database "{{ .POSTGRES_URL }}" down
  migrate:version: migrate -path internal/db/migrations -database "{{ .POSTGRES_URL }}" version
  templ:live:
    cmd: templ generate --watch --proxy="http://localhost:8080"
  dev:api:
    cmd: air --build.cmd "task sqlc && task swag && task build:api" --build.bin "bin\\api-backend.exe"
    env:
      ENVIRONMENT: development
  dev:tasks:
    cmd: air --build.cmd "task build:tasks" --build.bin "bin\\scheduled-tasks.exe" --build.exclude_dir "assets,tmp,vendor,testdata,bin,internal\\db,internal\\docs,api,handlers"
    env:
      ENVIRONMENT: development
  dev:compile-api-only:
    cmd: air --build.cmd "task build:api"
    env:
      ENVIRONMENT: development