version: '3'

tasks:
  migrate:
    # Some examples of how to use this:
    # - task migrate -- force {{VERSION}}
    # - task migrate -- up
    # - task migrate -- down
    # - task migrate -- version
    cmd: migrate -path internal/db/migrations -database "postgres://$DATABASE_USERNAME:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT?$DATABASE_OPTIONS" {{ .CLI_ARGS }}
    dotenv: ['./services/web/.env']

  sqlc:generate: cd internal/db && sqlc generate
  swagger:generate:
    cmds:
      - swag fmt
      - swag init -g services/web/cmd/main.go --output services/web/docs

  dev:web:
    cmd: go run ./services/web/cmd/main.go
    dotenv: ['./services/web/.env']

  dev:cron:
    cmd: go run ./services/cron/cmd/main.go
    dotenv: ['./services/cron/.env']