// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/guild/{guild_id}/activity-leaderboard-card": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The activity type.",
                        "name": "activity_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The time period.",
                        "name": "time_period",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/member/{member_id}": {
            "get": {
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/member/{member_id}/chat-activity": {
            "patch": {
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/member/{member_id}/migrate": {
            "post": {
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The migration body.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.MigrateMemberProfileBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/member/{member_id}/profile-card": {
            "get": {
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/settings": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GuildSettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GuildSettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        },
        "/v1/guild/{guild_id}/settings/activity": {
            "patch": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The activity settings.",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GuildActivitySettingsUpdateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GuildSettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        },
        "/v1/guild/{guild_id}/settings/activity-roles": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The activity settings.",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GuildActivityRoleCreateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GuildSettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        },
        "/v1/guild/{guild_id}/settings/message-embeds": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/voice-room-lobby/{origin_channel_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The channel ID for the lobby origin.",
                        "name": "origin_channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The channel ID for the lobby origin.",
                        "name": "origin_channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The channel ID for the lobby origin.",
                        "name": "origin_channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The channel ID for the lobby origin.",
                        "name": "origin_channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/voice-room-lobby/{origin_channel_id}/register": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The channel ID for the lobby origin.",
                        "name": "origin_channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/guild/{guild_id}/voice-room/{channel_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "channel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "handlers.APIError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.GuildActivityRoleCreateBody": {
            "type": "object",
            "properties": {
                "activity_type": {
                    "type": "string"
                },
                "required_points": {
                    "type": "integer"
                },
                "role_id": {
                    "type": "string"
                }
            }
        },
        "handlers.GuildActivitySettingsUpdateBody": {
            "type": "object"
        },
        "handlers.GuildSettingsResponse": {
            "type": "object"
        },
        "handlers.MigrateMemberProfileBody": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Guild endpoints.",
            "name": "Guilds"
        },
        {
            "description": "Voice room lobby endpoints.",
            "name": "Voice Room Lobbies"
        },
        {
            "description": "Voice room endpoints.",
            "name": "Voice Rooms"
        },
        {
            "description": "Member endpoints.",
            "name": "Members"
        },
        {
            "description": "HTML generation endpoints.",
            "name": "HTML Generation"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Discord Bot API",
	Description:      "The API for the main Typical Developers Discord bot.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
