// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/guild/{guild_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild/{guild_id}/create": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild/{guild_id}/member/{member_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemberProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild/{guild_id}/member/{member_id}/activity-points/increment": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "chat"
                        ],
                        "type": "string",
                        "description": "The activity type.",
                        "name": "activity_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemberProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild/{guild_id}/member/{member_id}/create": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The member ID.",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemberProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild/{guild_id}/update": {
            "patch": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.GenericResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ActivityConfig": {
            "type": "object",
            "properties": {
                "activity_roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ActivityRole"
                    }
                },
                "cooldown_seconds": {
                    "type": "integer"
                },
                "grant_amount": {
                    "type": "integer"
                },
                "is_enabled": {
                    "type": "boolean"
                }
            }
        },
        "models.ActivityRole": {
            "type": "object",
            "properties": {
                "required_points": {
                    "type": "integer"
                },
                "role_id": {
                    "type": "string"
                }
            }
        },
        "models.ActivityRoleProgress": {
            "type": "object",
            "properties": {
                "progress": {
                    "type": "integer"
                },
                "remaining_points": {
                    "type": "integer"
                },
                "required_points": {
                    "type": "integer"
                },
                "role_id": {
                    "type": "string"
                }
            }
        },
        "models.CardStyle": {
            "type": "integer",
            "enum": [
                0
            ],
            "x-enum-varnames": [
                "CardStyleDefault"
            ]
        },
        "models.GenericResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.GuildSettings": {
            "type": "object",
            "properties": {
                "chat_activity": {
                    "$ref": "#/definitions/models.ActivityConfig"
                }
            }
        },
        "models.MemberActivity": {
            "type": "object",
            "properties": {
                "is_on_cooldown": {
                    "type": "boolean"
                },
                "last_grant": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "roles": {
                    "$ref": "#/definitions/models.MemberRoles"
                }
            }
        },
        "models.MemberProfile": {
            "type": "object",
            "properties": {
                "card_style": {
                    "$ref": "#/definitions/models.CardStyle"
                },
                "chat_activity": {
                    "$ref": "#/definitions/models.MemberActivity"
                }
            }
        },
        "models.MemberRoles": {
            "type": "object",
            "properties": {
                "next": {
                    "$ref": "#/definitions/models.ActivityRoleProgress"
                },
                "obtained": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ActivityRole"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Guild endpoints.",
            "name": "Guilds"
        },
        {
            "description": "Member endpoints.",
            "name": "Members"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Discord Bot API",
	Description:      "The API for the main Typical Developers Discord bot.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
