// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/guild-settings/{guild_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild-settings/{guild_id}/create": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    }
                }
            }
        },
        "/guild-settings/{guild_id}/update": {
            "patch": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "tags": [
                    "Guilds"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The guild ID.",
                        "name": "guild_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GuildSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api_structures.GenericResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_structures.Activity": {
            "type": "object",
            "properties": {
                "activity_roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_structures.ActivityRole"
                    }
                },
                "cooldown_seconds": {
                    "type": "integer"
                },
                "grant_amount": {
                    "type": "integer"
                },
                "is_enabled": {
                    "type": "boolean"
                }
            }
        },
        "api_structures.ActivityRole": {
            "type": "object",
            "properties": {
                "required_points": {
                    "type": "integer"
                },
                "role_id": {
                    "type": "string"
                }
            }
        },
        "api_structures.GenericResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api_structures.GuildSettings": {
            "type": "object",
            "properties": {
                "chat_activity": {
                    "$ref": "#/definitions/api_structures.Activity"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Guild endpoints.",
            "name": "Guilds"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Discord Bot API",
	Description:      "The API for the main Typical Developers Discord bot.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
