definitions:
  models.APIResponse-ErrorResponse:
    properties:
      data:
        $ref: '#/definitions/models.ErrorResponse'
      success:
        type: boolean
    type: object
  models.APIResponse-GuildSettings:
    properties:
      data:
        $ref: '#/definitions/models.GuildSettings'
      success:
        type: boolean
    type: object
  models.APIResponse-MemberActivity:
    properties:
      data:
        $ref: '#/definitions/models.MemberActivity'
      success:
        type: boolean
    type: object
  models.APIResponse-MemberProfile:
    properties:
      data:
        $ref: '#/definitions/models.MemberProfile'
      success:
        type: boolean
    type: object
  models.APIResponse-array_models_ActivityRole:
    properties:
      data:
        items:
          $ref: '#/definitions/models.ActivityRole'
        type: array
      success:
        type: boolean
    type: object
  models.APIResponse-array_models_VoiceRoomLobbyConfig:
    properties:
      data:
        items:
          $ref: '#/definitions/models.VoiceRoomLobbyConfig'
        type: array
      success:
        type: boolean
    type: object
  models.APIResponse-models_VoiceRoomLobbyConfig:
    properties:
      data:
        $ref: '#/definitions/models.VoiceRoomLobbyConfig'
      success:
        type: boolean
    type: object
  models.ActivityConfig:
    properties:
      activity_roles:
        items:
          $ref: '#/definitions/models.ActivityRole'
        type: array
      cooldown_seconds:
        type: integer
      grant_amount:
        type: integer
      is_enabled:
        type: boolean
    type: object
  models.ActivityRole:
    properties:
      required_points:
        type: integer
      role_id:
        type: string
    type: object
  models.ActivityRoleProgress:
    properties:
      progress:
        type: integer
      required_points:
        type: integer
      role_id:
        type: string
    type: object
  models.ActivitySettings:
    properties:
      cooldown:
        type: integer
      enabled:
        type: boolean
      grant_amount:
        type: integer
    type: object
  models.ActivityType:
    enum:
    - chat
    type: string
    x-enum-varnames:
    - ActivityTypeChat
  models.AddActivityRole:
    properties:
      grant_type:
        $ref: '#/definitions/models.ActivityType'
      required_points:
        type: integer
      role_id:
        type: string
    type: object
  models.CardStyle:
    enum:
    - 0
    type: integer
    x-enum-varnames:
    - CardStyleDefault
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.GuildSettings:
    properties:
      chat_activity:
        $ref: '#/definitions/models.ActivityConfig'
      voice_rooms:
        items:
          $ref: '#/definitions/models.VoiceRoomLobbyConfig'
        type: array
    type: object
  models.MemberActivity:
    properties:
      is_on_cooldown:
        type: boolean
      last_grant:
        type: string
      points:
        type: integer
      rank:
        type: integer
      roles:
        $ref: '#/definitions/models.MemberRoles'
    type: object
  models.MemberProfile:
    properties:
      card_style:
        $ref: '#/definitions/models.CardStyle'
      chat_activity:
        $ref: '#/definitions/models.MemberActivity'
    type: object
  models.MemberRoles:
    properties:
      next:
        $ref: '#/definitions/models.ActivityRoleProgress'
      obtained:
        items:
          $ref: '#/definitions/models.ActivityRole'
        type: array
    type: object
  models.UpdateActivitySettings:
    properties:
      chat_activity:
        $ref: '#/definitions/models.ActivitySettings'
    type: object
  models.VoiceRoomLobbyConfig:
    properties:
      can_adjust_limit:
        type: boolean
      can_lock:
        type: boolean
      can_rename:
        type: boolean
      channel_id:
        type: string
      user_limit:
        type: integer
    type: object
  models.VoiceRoomLobbyModify:
    properties:
      can_adjust_limit:
        type: boolean
      can_lock:
        type: boolean
      can_rename:
        type: boolean
      user_limit:
        type: integer
    type: object
info:
  contact: {}
  description: The API for the main Typical Developers Discord bot.
  title: Discord Bot API
  version: "1.0"
paths:
  /{file}:
    get:
      parameters:
      - description: Asset file location.
        in: path
        name: file
        required: true
        type: string
      responses: {}
      tags:
      - HTML Generation
  /guild/{guild_id}/activity-leaderboard/card:
    get:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The activity type.
        enum:
        - chat
        in: query
        name: activity_type
        required: true
        type: string
      - description: The leaderboard display type.
        enum:
        - all
        - monthly
        - weekly
        in: query
        name: display
        required: true
        type: string
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      summary: Get the HTML generation for a member's profile card.
      tags:
      - HTML Generation
  /guild/{guild_id}/member/{member_id}/profile:
    get:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The member ID.
        in: path
        name: member_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-MemberProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Members
  /guild/{guild_id}/member/{member_id}/profile/card:
    get:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The member ID.
        in: path
        name: member_id
        required: true
        type: string
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      summary: Get the HTML generation for a member's profile card.
      tags:
      - HTML Generation
  /guild/{guild_id}/member/{member_id}/profile/create:
    post:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The member ID.
        in: path
        name: member_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-MemberProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Members
  /guild/{guild_id}/member/{member_id}/profile/increment-points:
    post:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The member ID.
        in: path
        name: member_id
        required: true
        type: string
      - description: The activity type.
        enum:
        - chat
        in: query
        name: activity_type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-MemberActivity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Members
  /guild/{guild_id}/settings:
    get:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-GuildSettings'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Guilds
  /guild/{guild_id}/settings/create:
    post:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-GuildSettings'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Guilds
  /guild/{guild_id}/settings/update/activity:
    patch:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The activity settings.
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/models.UpdateActivitySettings'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-GuildSettings'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Guilds
  /guild/{guild_id}/settings/update/add-activity-role:
    patch:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The activity settings.
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/models.AddActivityRole'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-array_models_ActivityRole'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Guilds
  /guild/{guild_id}/voice-room/lobby/{channel_id}:
    get:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The channel ID.
        in: path
        name: channel_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-models_VoiceRoomLobbyConfig'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Voice Room Lobbies
  /guild/{guild_id}/voice-room/lobby/{channel_id}/create:
    post:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The channel ID.
        in: path
        name: channel_id
        required: true
        type: string
      - description: The activity settings.
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/models.VoiceRoomLobbyModify'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-array_models_VoiceRoomLobbyConfig'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Voice Room Lobbies
  /guild/{guild_id}/voice-room/lobby/{channel_id}/delete:
    delete:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The channel ID.
        in: path
        name: channel_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-array_models_VoiceRoomLobbyConfig'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Voice Room Lobbies
  /guild/{guild_id}/voice-room/lobby/{channel_id}/update:
    patch:
      parameters:
      - description: The guild ID.
        in: path
        name: guild_id
        required: true
        type: string
      - description: The channel ID.
        in: path
        name: channel_id
        required: true
        type: string
      - description: The activity settings.
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/models.VoiceRoomLobbyModify'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse-models_VoiceRoomLobbyConfig'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse-ErrorResponse'
      security:
      - APIKeyAuth: []
      tags:
      - Voice Room Lobbies
securityDefinitions:
  APIKeyAuth:
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
tags:
- description: Guild endpoints.
  name: Guilds
- description: Voice room lobby endpoints.
  name: Voice Room Lobbies
- description: Voice room endpoints.
  name: Voice Rooms
- description: Member endpoints.
  name: Members
- description: HTML generation endpoints.
  name: HTML Generation
