// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild-leaderboards.sql

package db

import (
	"context"
)

const getAllTimeActivityLeaderboard = `-- name: GetAllTimeActivityLeaderboard :many
SELECT
    rankings.member_id,
    rankings.rank,
    rankings.points
FROM (
    SELECT 
        member_id,
        ROW_NUMBER() OVER (
            ORDER BY
                CASE LOWER($1)::TEXT
                    WHEN 'chat' THEN chat_activity
                    WHEN 'voice' THEN voice_activity
                END DESC,
                CASE LOWER($1)::TEXT
                    WHEN 'chat' THEN last_chat_activity_grant
                    WHEN 'voice' THEN last_voice_activity_grant
                END DESC
        ) AS rank,
        CAST (
            CASE LOWER($1)::TEXT
                WHEN 'chat' THEN chat_activity
                WHEN 'voice' THEN voice_activity
            END AS INT
        ) AS points
    FROM guild_profiles
    WHERE
        guild_profiles.guild_id = $2
) AS rankings
LIMIT $4
OFFSET $3
`

type GetAllTimeActivityLeaderboardParams struct {
	ActivityType string
	GuildID      string
	OffsetBy     int32
	LimitBy      int32
}

type GetAllTimeActivityLeaderboardRow struct {
	MemberID string
	Rank     int64
	Points   int32
}

func (q *Queries) GetAllTimeActivityLeaderboard(ctx context.Context, arg GetAllTimeActivityLeaderboardParams) ([]GetAllTimeActivityLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTimeActivityLeaderboard,
		arg.ActivityType,
		arg.GuildID,
		arg.OffsetBy,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTimeActivityLeaderboardRow
	for rows.Next() {
		var i GetAllTimeActivityLeaderboardRow
		if err := rows.Scan(&i.MemberID, &i.Rank, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyActivityLeaderboard = `-- name: GetMonthlyActivityLeaderboard :many
SELECT
    rankings.rank,
    rankings.member_id,
    rankings.earned_points
FROM (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY earned_points DESC
        ) AS rank,
        member_id,
        earned_points
    FROM guild_activity_tracking_monthly_current
    WHERE
        guild_id = $1
        AND grant_type = $2
) AS rankings
LIMIT 15
OFFSET $3
`

type GetMonthlyActivityLeaderboardParams struct {
	GuildID   string
	GrantType string
	OffsetBy  int32
}

type GetMonthlyActivityLeaderboardRow struct {
	Rank         int64
	MemberID     string
	EarnedPoints int32
}

func (q *Queries) GetMonthlyActivityLeaderboard(ctx context.Context, arg GetMonthlyActivityLeaderboardParams) ([]GetMonthlyActivityLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyActivityLeaderboard, arg.GuildID, arg.GrantType, arg.OffsetBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyActivityLeaderboardRow
	for rows.Next() {
		var i GetMonthlyActivityLeaderboardRow
		if err := rows.Scan(&i.Rank, &i.MemberID, &i.EarnedPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyActivityLeaderboard = `-- name: GetWeeklyActivityLeaderboard :many
SELECT
    rankings.rank,
    rankings.member_id,
    rankings.earned_points
FROM (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY earned_points DESC
        ) AS rank,
        member_id,
        earned_points
    FROM guild_activity_tracking_weekly_current
    WHERE
        guild_id = $1
        AND grant_type = $2
) AS rankings
LIMIT 15
OFFSET $3
`

type GetWeeklyActivityLeaderboardParams struct {
	GuildID   string
	GrantType string
	OffsetBy  int32
}

type GetWeeklyActivityLeaderboardRow struct {
	Rank         int64
	MemberID     string
	EarnedPoints int32
}

func (q *Queries) GetWeeklyActivityLeaderboard(ctx context.Context, arg GetWeeklyActivityLeaderboardParams) ([]GetWeeklyActivityLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyActivityLeaderboard, arg.GuildID, arg.GrantType, arg.OffsetBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyActivityLeaderboardRow
	for rows.Next() {
		var i GetWeeklyActivityLeaderboardRow
		if err := rows.Scan(&i.Rank, &i.MemberID, &i.EarnedPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementMonthlyActivityLeaderboard = `-- name: IncrementMonthlyActivityLeaderboard :exec
INSERT INTO guild_activity_tracking_monthly_current (
    grant_type, guild_id, member_id, earned_points
)
VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (grant_type, guild_id, member_id)
DO UPDATE SET
    earned_points = guild_activity_tracking_monthly_current.earned_points + $4
WHERE
    guild_activity_tracking_monthly_current.grant_type = $1
`

type IncrementMonthlyActivityLeaderboardParams struct {
	GrantType    string
	GuildID      string
	MemberID     string
	EarnedPoints int32
}

func (q *Queries) IncrementMonthlyActivityLeaderboard(ctx context.Context, arg IncrementMonthlyActivityLeaderboardParams) error {
	_, err := q.db.ExecContext(ctx, incrementMonthlyActivityLeaderboard,
		arg.GrantType,
		arg.GuildID,
		arg.MemberID,
		arg.EarnedPoints,
	)
	return err
}

const incrementWeeklyActivityLeaderboard = `-- name: IncrementWeeklyActivityLeaderboard :exec
INSERT INTO guild_activity_tracking_weekly_current (
    grant_type, guild_id, member_id, earned_points
)
VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (grant_type, guild_id, member_id)
DO UPDATE SET
    earned_points = guild_activity_tracking_weekly_current.earned_points + $4
WHERE
    guild_activity_tracking_weekly_current.grant_type = $1
`

type IncrementWeeklyActivityLeaderboardParams struct {
	GrantType    string
	GuildID      string
	MemberID     string
	EarnedPoints int32
}

func (q *Queries) IncrementWeeklyActivityLeaderboard(ctx context.Context, arg IncrementWeeklyActivityLeaderboardParams) error {
	_, err := q.db.ExecContext(ctx, incrementWeeklyActivityLeaderboard,
		arg.GrantType,
		arg.GuildID,
		arg.MemberID,
		arg.EarnedPoints,
	)
	return err
}
