// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type GuildActiveVoiceRoom struct {
	InsertEpoch     sql.NullInt32
	GuildID         string
	OriginChannelID string
	ChannelID       string
	CreatedByUserID string
	CurrentOwnerID  string
	IsLocked        sql.NullBool
}

type GuildActivityRole struct {
	InsertEpoch    sql.NullInt32
	GuildID        string
	RoleID         string
	RequiredPoints sql.NullInt32
	GrantType      string
}

type GuildActivityTrackingMonthly struct {
	MonthStart   int32
	GuildID      string
	MemberID     string
	EarnedPoints int32
	GrantType    string
}

type GuildActivityTrackingMonthlyCurrent struct {
	GrantType    string
	GuildID      string
	MemberID     string
	EarnedPoints int32
}

type GuildActivityTrackingWeekly struct {
	WeekStart    int32
	GuildID      string
	MemberID     string
	EarnedPoints int32
	GrantType    string
}

type GuildActivityTrackingWeeklyCurrent struct {
	GrantType    string
	GuildID      string
	MemberID     string
	EarnedPoints int32
}

type GuildProfile struct {
	InsertEpoch            sql.NullInt32
	GuildID                string
	MemberID               string
	CardStyle              int32
	ChatActivity           int32
	LastChatActivityGrant  int32
	VoiceActivity          int32
	LastVoiceActivityGrant int32
}

type GuildSetting struct {
	InsertEpoch           sql.NullInt32
	GuildID               string
	ChatActivityTracking  sql.NullBool
	ChatActivityGrant     sql.NullInt32
	ChatActivityCooldown  sql.NullInt32
	ChatActivityDenyRoles []string
	VoiceActivityTracking sql.NullBool
	VoiceActivityGrant    sql.NullInt32
	VoiceActivityCooldown sql.NullInt32
	VoiceGrantDeny        []string
}

type GuildVoiceRoomsSetting struct {
	InsertEpoch    sql.NullInt32
	GuildID        string
	VoiceChannelID string
	UserLimit      int32
	CanRename      bool
	CanLock        bool
	CanAdjustLimit bool
}
