// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GuildActiveVoiceRoom struct {
	InsertEpoch     pgtype.Int4
	GuildID         string
	OriginChannelID string
	ChannelID       string
	CreatedByUserID string
	CurrentOwnerID  string
	IsLocked        pgtype.Bool
}

type GuildActivityRole struct {
	InsertEpoch    pgtype.Int4
	GuildID        string
	RoleID         string
	RequiredPoints pgtype.Int4
	GrantType      string
}

type GuildActivityTrackingMonthly struct {
	MonthStart   int32
	GuildID      string
	MemberID     string
	EarnedPoints int32
	GrantType    string
}

type GuildActivityTrackingMonthlyCurrent struct {
	GrantType    string
	GuildID      string
	MemberID     string
	EarnedPoints int32
}

type GuildActivityTrackingWeekly struct {
	WeekStart    int32
	GuildID      string
	MemberID     string
	EarnedPoints int32
	GrantType    string
}

type GuildActivityTrackingWeeklyCurrent struct {
	GrantType    string
	GuildID      string
	MemberID     string
	EarnedPoints int32
}

type GuildProfile struct {
	InsertEpoch    pgtype.Int4
	GuildID        string
	MemberID       string
	CardStyle      int32
	ActivityPoints int32
	LastGrantEpoch int32
}

type GuildSetting struct {
	InsertEpoch              pgtype.Int4
	GuildID                  string
	ActivityTracking         pgtype.Bool
	ActivityTrackingGrant    pgtype.Int4
	ActivityTrackingCooldown pgtype.Int4
}

type GuildVoiceRoomsSetting struct {
	InsertEpoch    pgtype.Int4
	GuildID        string
	VoiceChannelID string
	UserLimit      int32
	CanRename      bool
	CanLock        bool
	CanAdjustLimit bool
}
