// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateGuildSettings(ctx context.Context, guildID string) (GuildSetting, error)
	CreateMemberProfile(ctx context.Context, arg CreateMemberProfileParams) (GuildProfile, error)
	GetAllTimeChatActivityRankings(ctx context.Context, arg GetAllTimeChatActivityRankingsParams) ([]GetAllTimeChatActivityRankingsRow, error)
	GetGuildActivityRoles(ctx context.Context, arg GetGuildActivityRolesParams) ([]GetGuildActivityRolesRow, error)
	GetGuildSettings(ctx context.Context, guildID string) (GetGuildSettingsRow, error)
	GetMemberProfile(ctx context.Context, arg GetMemberProfileParams) (GetMemberProfileRow, error)
	GetMemberRankings(ctx context.Context, arg GetMemberRankingsParams) (GetMemberRankingsRow, error)
	GetMonthlyActivityLeaderboard(ctx context.Context, arg GetMonthlyActivityLeaderboardParams) ([]GetMonthlyActivityLeaderboardRow, error)
	GetWeeklyActivityLeaderboard(ctx context.Context, arg GetWeeklyActivityLeaderboardParams) ([]GetWeeklyActivityLeaderboardRow, error)
	IncrememberMemberChatActivityPoints(ctx context.Context, arg IncrememberMemberChatActivityPointsParams) (GuildProfile, error)
	IncrementMonthlyActivityLeaderboard(ctx context.Context, arg IncrementMonthlyActivityLeaderboardParams) error
	IncrementWeeklyActivityLeaderboard(ctx context.Context, arg IncrementWeeklyActivityLeaderboardParams) error
	InsertActivityRole(ctx context.Context, arg InsertActivityRoleParams) error
	ResetMonthlyActivityLeaderboard(ctx context.Context) error
	ResetWeeklyActivityLeaderboard(ctx context.Context) error
	SetMemberChatActivityPoints(ctx context.Context, arg SetMemberChatActivityPointsParams) (GuildProfile, error)
	TruncateMonthlyActivityLeaderboard(ctx context.Context) error
	TruncateWeeklyActivityLeaderboard(ctx context.Context) error
	UpdateActivitySettings(ctx context.Context, arg UpdateActivitySettingsParams) error
}

var _ Querier = (*Queries)(nil)
