// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AppendGuildMessageEmbedSettingsArrays(ctx context.Context, arg AppendGuildMessageEmbedSettingsArraysParams) error
	ArchiveMonthlyActivityLeaderboard(ctx context.Context) error
	ArchiveWeeklyActivityLeaderboard(ctx context.Context) error
	CreateMemberProfile(ctx context.Context, arg CreateMemberProfileParams) (GuildProfile, error)
	CreateVoiceRoomLobby(ctx context.Context, arg CreateVoiceRoomLobbyParams) (GuildVoiceRoomsSetting, error)
	DeleteActivityRole(ctx context.Context, arg DeleteActivityRoleParams) error
	DeleteVoiceRoom(ctx context.Context, arg DeleteVoiceRoomParams) error
	DeleteVoiceRoomLobby(ctx context.Context, arg DeleteVoiceRoomLobbyParams) error
	FlushOudatedMonthlyActivityLeaderboard(ctx context.Context) error
	FlushOudatedWeeklyActivityLeaderboard(ctx context.Context) error
	GetActivityLeaderboardRankings(ctx context.Context, arg GetActivityLeaderboardRankingsParams) (GetActivityLeaderboardRankingsRow, error)
	GetAllTimeActivityLeaderboard(ctx context.Context, arg GetAllTimeActivityLeaderboardParams) ([]GetAllTimeActivityLeaderboardRow, error)
	GetAllTimeActivityLeaderboardPages(ctx context.Context, arg GetAllTimeActivityLeaderboardPagesParams) (int32, error)
	GetGuildActivityRoles(ctx context.Context, arg GetGuildActivityRolesParams) ([]GetGuildActivityRolesRow, error)
	GetGuildChatActivitySettings(ctx context.Context, guildID string) (GetGuildChatActivitySettingsRow, error)
	GetGuildMessageEmbedSettings(ctx context.Context, guildID string) (GetGuildMessageEmbedSettingsRow, error)
	GetGuildVoiceActivitySettings(ctx context.Context, guildID string) (GetGuildVoiceActivitySettingsRow, error)
	GetMemberChatActivityRoleInfo(ctx context.Context, arg GetMemberChatActivityRoleInfoParams) (GetMemberChatActivityRoleInfoRow, error)
	GetMemberProfile(ctx context.Context, arg GetMemberProfileParams) (GetMemberProfileRow, error)
	GetMonthlyActivityLeaderboard(ctx context.Context, arg GetMonthlyActivityLeaderboardParams) ([]GetMonthlyActivityLeaderboardRow, error)
	GetMonthlyActivityLeaderboardPages(ctx context.Context, arg GetMonthlyActivityLeaderboardPagesParams) (int32, error)
	GetMonthlyActivityLeaderboardResetDetails(ctx context.Context) (GetMonthlyActivityLeaderboardResetDetailsRow, error)
	GetVoiceRoom(ctx context.Context, arg GetVoiceRoomParams) (GuildActiveVoiceRoom, error)
	GetVoiceRoomIds(ctx context.Context, arg GetVoiceRoomIdsParams) ([]string, error)
	GetVoiceRoomLobbies(ctx context.Context, guildID string) ([]GetVoiceRoomLobbiesRow, error)
	GetVoiceRoomLobby(ctx context.Context, arg GetVoiceRoomLobbyParams) (GuildVoiceRoomsSetting, error)
	GetVoiceRooms(ctx context.Context, arg GetVoiceRoomsParams) ([]GuildActiveVoiceRoom, error)
	GetWeeklyActivityLeaderboard(ctx context.Context, arg GetWeeklyActivityLeaderboardParams) ([]GetWeeklyActivityLeaderboardRow, error)
	GetWeeklyActivityLeaderboardPages(ctx context.Context, arg GetWeeklyActivityLeaderboardPagesParams) (int32, error)
	GetWeeklyActivityLeaderboardResetDetails(ctx context.Context) (GetWeeklyActivityLeaderboardResetDetailsRow, error)
	IncrememberMemberChatActivityPoints(ctx context.Context, arg IncrememberMemberChatActivityPointsParams) (GuildProfile, error)
	IncrementMonthlyActivityLeaderboard(ctx context.Context, arg IncrementMonthlyActivityLeaderboardParams) error
	IncrementWeeklyActivityLeaderboard(ctx context.Context, arg IncrementWeeklyActivityLeaderboardParams) error
	InsertActivityRole(ctx context.Context, arg InsertActivityRoleParams) error
	MigrateMemberProfile(ctx context.Context, arg MigrateMemberProfileParams) error
	RegisterGuild(ctx context.Context, guildID string) (Guild, error)
	RegisterVoiceRoom(ctx context.Context, arg RegisterVoiceRoomParams) (GuildActiveVoiceRoom, error)
	RemoveGuildMessageEmbedSettingsArrays(ctx context.Context, arg RemoveGuildMessageEmbedSettingsArraysParams) error
	ResetMemberProfile(ctx context.Context, arg ResetMemberProfileParams) error
	UpdateGuildChatActivitySettings(ctx context.Context, arg UpdateGuildChatActivitySettingsParams) error
	UpdateGuildMessageEmbedSettings(ctx context.Context, arg UpdateGuildMessageEmbedSettingsParams) error
	UpdateGuildVoiceActivitySettings(ctx context.Context, arg UpdateGuildVoiceActivitySettingsParams) error
	UpdateVoiceRoom(ctx context.Context, arg UpdateVoiceRoomParams) (GuildActiveVoiceRoom, error)
	UpdateVoiceRoomLobby(ctx context.Context, arg UpdateVoiceRoomLobbyParams) (GuildVoiceRoomsSetting, error)
}

var _ Querier = (*Queries)(nil)
